# 这是一个帮助您开始使用Actions的基本工作流

name: Webfonts

# 控制工作流何时运行
on:
  # 在push或pull request事件触发工作流，但仅限于"main"分支
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # 允许您从Actions选项卡手动运行此工作流
  workflow_dispatch:

# 工作流运行由一个或多个可以按顺序或并行运行的作业组成
jobs:
  # 此工作流包含一个名为"build"的作业
  build:
    # 作业将在其上运行的运行器类型
    runs-on: macos-latest

    # 步骤表示作为作业一部分将执行的任务序列
    steps:
      # 检出您的仓库到$GITHUB_WORKSPACE下，以便您的作业可以访问它
      - name: Checkout repository
        uses: actions/checkout@v4

      # 确保source目录存在
      - name: Check source directory
        run: |
          if [ ! -d "source" ]; then
            echo "Source directory not found!"
            exit 1
          fi
          echo "Using files from source directory"

      # 创建dist目录
      - name: Create dist directory
        run: mkdir -p dist

      # 设置Node.js环境
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.14.0'
          
      # 安装依赖
      - name: Install dependencies
        run: npm i
        
      # 构建项目
      - name: Build project
        run: npm run build

      # 打包dist目录
      - name: Create dist archive
        run: |
          cd dist
          zip -r ../webfonts-dist.zip .
          cd ..
          echo "Created dist archive"

      # 上传构建产物
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: webfonts-dist
          path: webfonts-dist.zip
          retention-days: 7
